#!/usr/bin/env node

/**
 * 🤖 AI Career Automation Script
 * Integrated automation system for GitHub Actions and n8n workflows
 */

const fs = require('fs');
const path = require('path');
const https = require('https');

class CareerAutomationSystem {
    constructor() {
        this.config = this.loadConfig();
        this.startTime = Date.now();
        this.results = {
            portfolio: false,
            social: false,
            webhook: false,
            analytics: false
        };
    }

    loadConfig() {
        const defaultConfig = {
            openaiApiKey: process.env.OPENAI_API_KEY,
            geminiApiKey: process.env.GEMINI_API_KEY,
            n8nWebhookUrl: process.env.N8N_WEBHOOK_URL,
            githubToken: process.env.GITHUB_TOKEN,
            repository: process.env.GITHUB_REPOSITORY,
            branch: process.env.GITHUB_REF_NAME,
            commit: process.env.GITHUB_SHA,
            automation: {
                enabled: process.env.AUTOMATION_ENABLED !== 'false',
                timezone: process.env.TIMEZONE || 'Asia/Kolkata',
                dailyTime: process.env.DAILY_AUTOMATION_TIME || '09:00'
            }
        };
        return defaultConfig;
    }

    async run() {
        console.log('🚀 Starting AI Career Automation System...');
        console.log(`📅 Timestamp: ${new Date().toISOString()}`);
        console.log(`📁 Repository: ${this.config.repository}`);
        console.log(`🌿 Branch: ${this.config.branch}`);
        console.log(`📝 Commit: ${this.config.commit?.substring(0, 7)}`);

        try {
            // Step 1: Generate Portfolio Content
            await this.generatePortfolioContent();
            
            // Step 2: Update Social Media Templates
            await this.updateSocialMediaTemplates();
            
            // Step 3: Trigger n8n Webhook
            await this.triggerN8nWebhook();
            
            // Step 4: Generate Analytics
            await this.generateAnalytics();
            
            console.log('\n✅ Automation completed successfully!');
            this.printResults();
            
        } catch (error) {
            console.error('❌ Automation failed:', error.message);
            process.exit(1);
        }
    }

    async generatePortfolioContent() {
        console.log('\n📚 Generating Portfolio Content...');
        
        const projectData = {
            name: 'AI Career Automation System',
            description: 'Complete biotech & bioinformatics career automation platform with AI-powered content generation',
            technologies: ['Node.js', 'TypeScript', 'GitHub Actions', 'n8n', 'AI APIs'],
            features: [
                'Automated portfolio generation',
                'Social media content creation',
                'Job application tracking',
                'AI-powered prompts library',
                'Analytics dashboard'
            ],
            targetAudience: 'Biotech & Bioinformatics Professionals',
            lastUpdated: new Date().toISOString()
        };

        // Generate AI-powered content (simulated for now)
        const aiContent = this.generateAIContent(projectData);
        
        // Update portfolio files
        await this.updatePortfolioFiles(aiContent);
        
        this.results.portfolio = true;
        console.log('✅ Portfolio content generated and updated');
    }

    generateAIContent(projectData) {
        return {
            readme: `# 🤖 ${projectData.name}

## Overview
${projectData.description}

## 🎯 Key Features
${projectData.features.map(feature => `- ✅ ${feature}`).join('\n')}

## 🛠️ Technologies Used
${projectData.technologies.map(tech => `- ${tech}`).join('\n')}

## 🎯 Target Audience
${projectData.targetAudience}

## 📅 Last Updated
${new Date(projectData.lastUpdated).toLocaleDateString()}

---
*This content was automatically generated by our AI Career Automation System*`,

            linkedinPost: `🚀 Exciting progress on our AI Career Automation System!

Just deployed updates that include:
✅ Automated portfolio generation
✅ Social media content creation
✅ Real-time job tracking
✅ AI-powered career optimization

Perfect for biotech & bioinformatics professionals looking to accelerate their career growth!

Technologies: ${projectData.technologies.slice(0, 3).join(', ')}

#BiotechCareers #AIAutomation #Bioinformatics #CareerGrowth #TechInnovation`,

            twitterPost: `🤖 New: AI Career Automation System update!

✅ Auto portfolio generation
✅ Social media templates  
✅ Job tracking dashboard
✅ AI-powered content

Perfect for #biotech professionals! 

#CareerAutomation #AI #BiotechJobs`
        };
    }

    async updatePortfolioFiles(content) {
        // Update README with automation status
        const readmePath = path.join(process.cwd(), 'README.md');
        if (fs.existsSync(readmePath)) {
            let readme = fs.readFileSync(readmePath, 'utf8');
            
            const automationSection = `

## 🤖 Automated Updates
**Last automated update:** ${new Date().toISOString()}  
**System status:** ✅ Active  
**Next scheduled run:** ${this.getNextScheduledRun()}

### Recent Automation Activities
- ✅ Portfolio content refreshed
- ✅ Social media templates updated
- ✅ Job tracking optimized
- ✅ AI prompts enhanced

---
*Powered by AI Career Automation System*`;

            if (!readme.includes('🤖 Automated Updates')) {
                readme += automationSection;
                fs.writeFileSync(readmePath, readme);
            }
        }

        // Create/update automation status file
        const statusData = {
            lastRun: new Date().toISOString(),
            status: 'success',
            features: {
                portfolioGeneration: true,
                socialMediaTemplates: true,
                jobTracking: true,
                aiPrompts: true
            },
            nextScheduledRun: this.getNextScheduledRun(),
            repository: this.config.repository,
            commit: this.config.commit
        };

        fs.writeFileSync(
            path.join(process.cwd(), 'automation-status.json'),
            JSON.stringify(statusData, null, 2)
        );
    }

    async updateSocialMediaTemplates() {
        console.log('\n📱 Updating Social Media Templates...');
        
        const templates = this.generateSocialMediaTemplates();
        
        const templateFile = path.join(process.cwd(), 'Social_Media_Templates.md');
        const dailySection = `

## 📅 Daily Automation Updates - ${new Date().toLocaleDateString()}

### LinkedIn Professional Post Template
\`\`\`
${templates.linkedin}
\`\`\`

### Twitter Update Template
\`\`\`
${templates.twitter}
\`\`\`

### Facebook Professional Update
\`\`\`
${templates.facebook}
\`\`\`

---
*Templates auto-generated by AI Career Automation System*`;

        if (fs.existsSync(templateFile)) {
            let content = fs.readFileSync(templateFile, 'utf8');
            if (!content.includes(`Daily Automation Updates - ${new Date().toLocaleDateString()}`)) {
                content += dailySection;
                fs.writeFileSync(templateFile, content);
            }
        }

        this.results.social = true;
        console.log('✅ Social media templates updated');
    }

    generateSocialMediaTemplates() {
        const date = new Date().toLocaleDateString();
        
        return {
            linkedin: `🚀 AI Career Automation System Update - ${date}

Just enhanced our biotech career automation platform with:
✅ Smart portfolio generation
✅ AI-powered content creation
✅ Automated job tracking
✅ Real-time analytics dashboard

Key benefits for biotech professionals:
🔬 Save 10+ hours/week on content creation
📈 Increase application response rates by 40%
🤖 AI-optimized personal branding
🎯 Targeted job search automation

Perfect for bioinformatics, pharmaceutical, and biotechnology professionals!

#Biotechnology #Bioinformatics #CareerAutomation #AI #BiotechJobs #TechInnovation`,

            twitter: `🤖 AI Career Automation Update!

New features live:
✅ Auto portfolio builder
✅ Social media templates
✅ Job tracking dashboard
✅ AI-powered prompts

Perfect for #biotech professionals looking to accelerate their career!

#BiotechCareers #AIAutomation #Bioinformatics #TechJobs`,

            facebook: `🎉 Exciting Update: AI Career Automation System

Our latest enhancements make career growth easier for biotech professionals:

🔬 Automated Portfolio Generation - Create professional project documentation in minutes
📱 Social Media Content - AI-generated posts for LinkedIn, Twitter, and Facebook  
💼 Job Application Tracking - Smart dashboard to monitor applications and responses
🤖 AI Prompt Library - Ready-to-use prompts for all major AI tools

This system is specifically designed for biotechnology and bioinformatics professionals who want to:
- Build a strong online presence
- Streamline job search process
- Create engaging professional content
- Track career progress effectively

Try it out and transform your career journey with AI! 🚀

#Biotechnology #CareerDevelopment #AIAutomation #ProfessionalGrowth`
        };
    }

    async triggerN8nWebhook() {
        console.log('\n🔗 Triggering n8n Webhook...');
        
        if (!this.config.n8nWebhookUrl) {
            console.log('⚠️ N8N_WEBHOOK_URL not configured - skipping webhook');
            return;
        }

        const payload = {
            event: 'github_automation_trigger',
            repository: this.config.repository,
            commit: this.config.commit,
            branch: this.config.branch,
            timestamp: new Date().toISOString(),
            workflow: 'ai-career-automation',
            data: {
                portfolio_updated: this.results.portfolio,
                social_templates_updated: this.results.social,
                automation_status: 'active',
                next_scheduled_run: this.getNextScheduledRun(),
                execution_time: Date.now() - this.startTime
            }
        };

        try {
            await this.makeHttpRequest(
                `${this.config.n8nWebhookUrl}/webhook/balaji-automation`,
                'POST',
                payload
            );
            
            this.results.webhook = true;
            console.log('✅ n8n webhook triggered successfully');
        } catch (error) {
            console.log('⚠️ Webhook trigger failed:', error.message);
            // Don't fail the entire process for webhook issues
        }
    }

    async generateAnalytics() {
        console.log('\n📊 Generating Analytics Report...');
        
        const analytics = {
            timestamp: new Date().toISOString(),
            workflow_run: process.env.GITHUB_RUN_NUMBER || 'local',
            repository: this.config.repository,
            branch: this.config.branch,
            commit: this.config.commit,
            execution_time_ms: Date.now() - this.startTime,
            automation_results: this.results,
            system_status: {
                portfolio_generation: this.results.portfolio ? '✅ Success' : '❌ Failed',
                social_media_templates: this.results.social ? '✅ Updated' : '❌ Failed',
                webhook_trigger: this.results.webhook ? '✅ Triggered' : '⚠️ Skipped',
                overall_status: Object.values(this.results).every(r => r) ? 'Success' : 'Partial'
            },
            next_actions: [
                'Review generated content and customize as needed',
                'Schedule social media posts using provided templates',
                'Monitor n8n workflow execution for additional automation',
                'Check automation-status.json for detailed results'
            ],
            configuration_status: {
                openai_api_key: this.config.openaiApiKey ? '✅ Configured' : '⚠️ Missing',
                gemini_api_key: this.config.geminiApiKey ? '✅ Configured' : '⚠️ Missing', 
                n8n_webhook_url: this.config.n8nWebhookUrl ? '✅ Configured' : '⚠️ Missing',
                github_token: this.config.githubToken ? '✅ Configured' : '⚠️ Missing'
            }
        };

        fs.writeFileSync(
            path.join(process.cwd(), 'automation-analytics.json'),
            JSON.stringify(analytics, null, 2)
        );

        this.results.analytics = true;
        console.log('✅ Analytics report generated');
        
        return analytics;
    }

    makeHttpRequest(url, method, data) {
        return new Promise((resolve, reject) => {
            const urlObj = new URL(url);
            const postData = JSON.stringify(data);
            
            const options = {
                hostname: urlObj.hostname,
                port: urlObj.port || 443,
                path: urlObj.pathname + urlObj.search,
                method: method,
                headers: {
                    'Content-Type': 'application/json',
                    'Content-Length': Buffer.byteLength(postData),
                    'User-Agent': 'AI-Career-Automation/1.0'
                }
            };

            const req = https.request(options, (res) => {
                let responseData = '';
                res.on('data', (chunk) => responseData += chunk);
                res.on('end', () => {
                    if (res.statusCode >= 200 && res.statusCode < 300) {
                        resolve(responseData);
                    } else {
                        reject(new Error(`HTTP ${res.statusCode}: ${responseData}`));
                    }
                });
            });

            req.on('error', reject);
            req.write(postData);
            req.end();
        });
    }

    getNextScheduledRun() {
        const tomorrow = new Date();
        tomorrow.setDate(tomorrow.getDate() + 1);
        tomorrow.setHours(9, 0, 0, 0); // 9 AM IST
        return tomorrow.toISOString();
    }

    printResults() {
        console.log('\n📋 Automation Results Summary:');
        console.log(`├── Portfolio Generation: ${this.results.portfolio ? '✅' : '❌'}`);
        console.log(`├── Social Media Templates: ${this.results.social ? '✅' : '❌'}`);
        console.log(`├── Webhook Trigger: ${this.results.webhook ? '✅' : '⚠️'}`);
        console.log(`└── Analytics Report: ${this.results.analytics ? '✅' : '❌'}`);
        console.log(`\n⏱️ Total execution time: ${Date.now() - this.startTime}ms`);
        console.log(`🎯 Next scheduled run: ${this.getNextScheduledRun()}`);
    }
}

// Run the automation if this script is executed directly
if (require.main === module) {
    const automation = new CareerAutomationSystem();
    automation.run().catch(error => {
        console.error('Fatal error:', error);
        process.exit(1);
    });
}

module.exports = CareerAutomationSystem;