// GitHub API Integration Module
// Secure GitHub API automation for career development

class GitHubAPI {
    constructor() {
        this.baseURL = 'https://api.github.com';
        this.token = null;
        this.username = null;
        this.initialized = false;
    }

    // Initialize with API token (supports environment variables or user input)
    initialize(token, username) {
        if (!token || !username) {
            console.warn('GitHub API token or username not provided');
            return false;
        }
        
        this.token = token;
        this.username = username;
        this.initialized = true;
        return true;
    }

    // Check if API is properly initialized
    isInitialized() {
        return this.initialized && this.token && this.username;
    }

    // Create headers for API requests
    getHeaders() {
        return {
            'Authorization': `token ${this.token}`,
            'Accept': 'application/vnd.github.v3+json',
            'Content-Type': 'application/json',
            'User-Agent': 'Career-Automation-Dashboard'
        };
    }

    // Create a new repository
    async createRepository(repoData) {
        if (!this.isInitialized()) {
            throw new Error('GitHub API not initialized. Please provide valid token and username.');
        }

        const url = `${this.baseURL}/user/repos`;
        
        const payload = {
            name: repoData.name,
            description: repoData.description || 'Generated by AI Career Automation Dashboard',
            private: repoData.private || false,
            has_issues: true,
            has_projects: true,
            has_wiki: true,
            auto_init: true,
            ...repoData
        };

        try {
            const response = await fetch(url, {
                method: 'POST',
                headers: this.getHeaders(),
                body: JSON.stringify(payload)
            });

            if (!response.ok) {
                const error = await response.json();
                throw new Error(`Failed to create repository: ${error.message}`);
            }

            return await response.json();
        } catch (error) {
            console.error('Error creating repository:', error);
            throw error;
        }
    }

    // Create or update a file in repository
    async createOrUpdateFile(repoName, filePath, content, commitMessage, branch = 'main') {
        if (!this.isInitialized()) {
            throw new Error('GitHub API not initialized. Please provide valid token and username.');
        }

        const url = `${this.baseURL}/repos/${this.username}/${repoName}/contents/${filePath}`;
        
        // First, try to get the file to see if it exists
        let sha = null;
        try {
            const existingFile = await fetch(url, {
                headers: this.getHeaders()
            });
            
            if (existingFile.ok) {
                const fileData = await existingFile.json();
                sha = fileData.sha;
            }
        } catch (error) {
            // File doesn't exist, which is fine for creation
        }

        const payload = {
            message: commitMessage,
            content: btoa(unescape(encodeURIComponent(content))), // Base64 encode with UTF-8 support
            branch: branch
        };

        if (sha) {
            payload.sha = sha; // Required for updates
        }

        try {
            const response = await fetch(url, {
                method: 'PUT',
                headers: this.getHeaders(),
                body: JSON.stringify(payload)
            });

            if (!response.ok) {
                const error = await response.json();
                throw new Error(`Failed to create/update file: ${error.message}`);
            }

            return await response.json();
        } catch (error) {
            console.error('Error creating/updating file:', error);
            throw error;
        }
    }

    // Get user repositories
    async getUserRepositories() {
        if (!this.isInitialized()) {
            throw new Error('GitHub API not initialized. Please provide valid token and username.');
        }

        const url = `${this.baseURL}/user/repos?sort=updated&per_page=100`;
        
        try {
            const response = await fetch(url, {
                headers: this.getHeaders()
            });

            if (!response.ok) {
                const error = await response.json();
                throw new Error(`Failed to fetch repositories: ${error.message}`);
            }

            return await response.json();
        } catch (error) {
            console.error('Error fetching repositories:', error);
            throw error;
        }
    }

    // Get user profile information
    async getUserProfile() {
        if (!this.isInitialized()) {
            throw new Error('GitHub API not initialized. Please provide valid token and username.');
        }

        const url = `${this.baseURL}/user`;
        
        try {
            const response = await fetch(url, {
                headers: this.getHeaders()
            });

            if (!response.ok) {
                const error = await response.json();
                throw new Error(`Failed to fetch user profile: ${error.message}`);
            }

            return await response.json();
        } catch (error) {
            console.error('Error fetching user profile:', error);
            throw error;
        }
    }

    // Validate API token
    async validateToken() {
        if (!this.token) {
            return false;
        }

        try {
            const response = await fetch(`${this.baseURL}/user`, {
                headers: {
                    'Authorization': `token ${this.token}`,
                    'Accept': 'application/vnd.github.v3+json'
                }
            });

            return response.ok;
        } catch (error) {
            console.error('Error validating token:', error);
            return false;
        }
    }

    // Create a complete project with README, folder structure, etc.
    async createCompleteProject(projectData) {
        if (!this.isInitialized()) {
            throw new Error('GitHub API not initialized. Please provide valid token and username.');
        }

        try {
            // Create repository
            const repo = await this.createRepository({
                name: projectData.name,
                description: projectData.description,
                private: projectData.private || false
            });

            // Create README.md
            if (projectData.readme) {
                await this.createOrUpdateFile(
                    projectData.name,
                    'README.md',
                    projectData.readme,
                    'Add comprehensive README.md'
                );
            }

            // Create additional files if provided
            if (projectData.files && Array.isArray(projectData.files)) {
                for (const file of projectData.files) {
                    await this.createOrUpdateFile(
                        projectData.name,
                        file.path,
                        file.content,
                        file.commitMessage || `Add ${file.path}`
                    );
                }
            }

            return {
                success: true,
                repository: repo,
                message: 'Project created successfully!'
            };

        } catch (error) {
            console.error('Error creating complete project:', error);
            return {
                success: false,
                error: error.message
            };
        }
    }

    // Automation for book/task management (interpreting the "marriage party" requirements)
    async automateBookManagement(books) {
        if (!this.isInitialized()) {
            throw new Error('GitHub API not initialized. Please provide valid token and username.');
        }

        const results = [];

        try {
            for (const book of books) {
                const projectResult = await this.createCompleteProject({
                    name: `book-${book.title.toLowerCase().replace(/\s+/g, '-')}`,
                    description: `Automated book management for: ${book.title}`,
                    readme: this.generateBookREADME(book),
                    private: book.private || false,
                    files: [
                        {
                            path: 'book-details.json',
                            content: JSON.stringify(book, null, 2),
                            commitMessage: 'Add book details JSON'
                        },
                        {
                            path: 'tasks.md',
                            content: this.generateTasksList(book),
                            commitMessage: 'Add tasks and checklist'
                        }
                    ]
                });

                results.push({
                    book: book.title,
                    result: projectResult
                });
            }

            return {
                success: true,
                results: results,
                message: 'Book automation completed successfully!'
            };

        } catch (error) {
            console.error('Error in book automation:', error);
            return {
                success: false,
                error: error.message
            };
        }
    }

    // Generate README for book projects
    generateBookREADME(book) {
        return `# ${book.title}

## 📖 Book Information

**Title:** ${book.title}
**Author:** ${book.author || 'Not specified'}
**Category:** ${book.category || 'General'}
**Status:** ${book.status || 'In Progress'}

## 📝 Description

${book.description || 'No description provided'}

## ✅ Tasks

- [ ] Read and analyze
- [ ] Create summary
- [ ] Extract key points
- [ ] Write review
- [ ] Share insights

## 📊 Progress Tracking

This repository tracks the progress and insights for "${book.title}".

## 🚀 Generated by AI Career Automation Dashboard

This project was automatically created using the AI Career Automation Dashboard.

---

*Last updated: ${new Date().toISOString().split('T')[0]}*
`;
    }

    // Generate tasks list for book management
    generateTasksList(book) {
        return `# Tasks for "${book.title}"

## 📋 Main Tasks

- [ ] **Initial Setup**
  - [x] Create repository
  - [x] Add book details
  - [ ] Set reading schedule

- [ ] **Reading Phase**
  - [ ] Chapter 1 review
  - [ ] Chapter 2 review
  - [ ] Key concepts extraction
  - [ ] Note-taking

- [ ] **Analysis Phase**
  - [ ] Summary creation
  - [ ] Critical analysis
  - [ ] Practical applications
  - [ ] Related research

- [ ] **Completion Phase**
  - [ ] Final review
  - [ ] Documentation
  - [ ] Share insights
  - [ ] Archive materials

## 🎯 Goals

- Complete reading by target date
- Extract actionable insights
- Create comprehensive notes
- Share learnings with team

---

*Task list generated automatically on ${new Date().toLocaleDateString()}*
`;
    }
}

// Create global instance
window.GitHubAPI = new GitHubAPI();

// Environment variable support (for server-side usage)
if (typeof process !== 'undefined' && process.env) {
    const token = process.env.GITHUB_TOKEN;
    const username = process.env.GITHUB_USERNAME;
    
    if (token && username) {
        window.GitHubAPI.initialize(token, username);
        console.log('GitHub API initialized from environment variables');
    }
}